### ISSUE TITLE
Camera Server / Performances

### ISSUE THREAD

**Issue by ghost** [headupinclouds/gatherer#142]
Hi guys,

Hope you are all well !

I was checking your great repository through Hunter project, and I was wondering if a camera server with  would solve any memory leak problems on iOS or Android ?
eg. https://github.com/Moonware/cordova-cameraserver

Maybe using thrift with asio or thread-pool-cpp would making performances even better:
eg: https://github.com/beschulz/thrift_asio

Last question, did u ever consider to integrate the "Godot" game engine to your gatherer project ?
https://github.com/godotengine/godot

Cheers,
Luc
##

**Comment by headupinclouds** [comment]
Hi Luc,

I'm doing well, thanks.  The gatherer project has mostly been a showcase and sandbox for hunter based cross platform video processing with ogles_gpgpu and QT (similar to GPUImage).  There is quite a lot of boilerplate code and devops work required to create performant cross platform computer vision projects, and this should hopefully provide some reusable libraries or at least project templates to get started.  I'm not familiar with the `cordova-cameraserver` project, but at first glance it seems to be targeting http streaming, not native camera based processing.  

After some experimentation, the best overall cross platform camera solution seems to be provided by the QT QML camera interface currently used in the qmlvideofilter app.  (I've been away from that for a while and need to update it to include some interface changes in the ogles_gpgpu package.)  Under the hood, QT is providing native OpenGL texture video frames on Android (via Graphics Buffers) and on iOS we are using minimal GLSL shader based NV12 (luminance + chroma) to RGBA texture conversions (lifted from GPUImage).  I don't expect there is much wasted processing with the basic pipeline, but let me know if you see room for improvement.  What frame rates are you seeing, and on which platforms?

> Maybe using thrift with asio or thread-pool-cpp would making performances even better

`thread-pool-cpp` is a sleek thread pool implementation.  I have been experimenting with that in another QT/QML app for some lightweight low resolution CPU processing.  I will try to add a simple example, since I tend to find most real world computer vision processing usually requires at least some low resolution CPU based processing.  So far that has been a great solution.  For the basic GPU video pipelines, I don't think thread pools can help much.

> Last question, did u ever consider to integrate the "Godot" game engine to your gatherer project 

I haven't see that.  I would like to have a lightweight cross platform rendering/game engine sample in this project.  There is currently an open hunter issue for `Urho3d` (see: ruslo/hunter#389), which is getting some attention.  The `gameplay3d` project seems to be another option, but since I have no personal experience or preference for either, I'd probably go with Urho3D if it becomes available through hunter.  Do you have experience with Godot or these other engines?

There are some WIP issues related to QT builds that should address some travis timeouts we were hitting, and that should help with overall project stability when they become available in hunter soon.

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
