### ISSUE TITLE
Adding Find-Object

### ISSUE THREAD

**Issue by ghost** [headupinclouds/gatherer#145]
Hi David,

Hope you are doing well !

I will make a fork of "Gatherer" in order to add the following project, as soon as I can compile the repo for iOS/xcode: https://github.com/introlab/find-object. Any objections ?! :-)

It is a simple Qt interface to try OpenCV implementations of SIFT (RootSift, ASIFT), AKAZE, SURF, FAST, BRIEF and other feature detectors and descriptors. It integrates a desktop UI, and a console mode. The great point is the inverted visual dictionary, with multi-detection, with a settings section (based on a .ini file) to switch the detectors and the descriptors to perform the visual search. 

You can either have a fixed visual dictionary loaded at the bootstrap from a .yaml file, or to rebuild the visual dictionary depending on your settings by keeping the images in memory; that can allow to enhance some performances tests in order to get the best false, positive rates from your mobile device, or the size of the visual bag of words.

For sure, lots of optimizations need to be done to keep all the task running on a mobile device like the camera binding, converting the camera scene to an OpenCV matrix, avoid matrix copies as much as possible, printing/drawing informations on the device view,  and the some selective search features.

Do you have any good recommendations in order to manage the settings view on mobile devices (something like https://github.com/phimage/Prephirences but with the settings view dynamically built) , Android for keeping the cross-platform spirit of your project ? I could not find something to parse an ini file and build a UI for editing the values for both.

After this milestone reached, I think that would build up a good ground to add after other features, like some tracking libs like libCMT, LSD-SLAM, ORB-SLAM2.

Excerpt of the .ini file:

```
[Homography]
allCornersVisible=false
homographyComputed=true
ignoreWhenAllInliers=false
method="1:LMEDS;RANSAC;RHO"
minAngle=0
minimumInliers=10
opticalFlow=false
opticalFlowEps=0.01
opticalFlowIterations=30
opticalFlowMaxLevel=3
opticalFlowWinSize=16
ransacReprojThr=5
rectBorderWidth=4

[NearestNeighbor]
1Strategy="1:Linear;KDTree;KMeans;Composite;Autotuned;Lsh;BruteForce"
2Distance_type="0:EUCLIDEAN_L2;MANHATTAN_L1;MINKOWSKI;MAX;HIST_INTERSECT;HELLINGER;CHI_SQUARE_CS;KULLBACK_LEIBLER_KL;HAMMING"
3nndrRatioUsed=true
4nndrRatio=0.8
5minDistanceUsed=false
6minDistance=1.6
7ConvertBinToFloat=false
Autotuned_build_weight=0.01
Autotuned_memory_weight=0
Autotuned_sample_fraction=0.10000000000000001
Autotuned_target_precision=0.80000000000000004
BruteForce_gpu=false
Composite_branching=32
Composite_cb_index=0.20000000000000001
Composite_centers_init="0:RANDOM;GONZALES;KMEANSPP"
Composite_iterations=11
Composite_trees=4
KDTree_trees=4
KMeans_branching=32
KMeans_cb_index=0.20000000000000001
KMeans_centers_init="0:RANDOM;GONZALES;KMEANSPP"
KMeans_iterations=11
Lsh_key_size=20
Lsh_multi_probe_level=2
Lsh_table_number=12
search_checks=32
search_eps=0
```

I wish you a great day. (Btw, I am in NYC too but going back to Europe the 2nd of May. ^^)

Cheers,
Luc Michalski

**Comment by headupinclouds** [comment]
> https://github.com/introlab/find-object. Any objections ?! :-)

That looks like a cool project, but it seems to be a self contained application/UI aimed at feature based matching and visualization.  Why not create a fork and hunterize the dependencies (Qt, OpenCV, etc)?

I've added some initial low level feature detection functionality to ogles_gpgpu (i.e., Shi-Tomasi corner detection from GPUImage, etc).  The ogles_gpgpu lib is being maintained as a submodule, until it is mature enough to migrate to hunter.  (The thread-pool-cpp lib is also a submodule in the 3rdparty lib.)  I'll add a working real time example to gatherer, which could be a good starting point for some of the processing you mention.  BTW, there is an open issue for the TheiaSfM package in hunter (ruslo/hunter/#276), which seems relevant to your interests.

Also, @ruslo has added a hunter package for ArrayFire, which has some OpenCL optimized feature matching implementations that I _think_ will run on Android: https://github.com/ruslo/hunter/wiki/pkg.arrayfire, but nobody has had time to try it out yet.  The commercial friendly ORB feature matching demo looks really cool: http://arrayfire.com/feature-detection-and-tracking-using-arrayfire (Android only due to OpenCL).

> Do you have any good recommendations in order to manage the settings view on mobile devices 

I'm not sure I understand exactly what you are looking for.  Are you looking for some kind of ini/json/yaml parsers for config files, or something more specific to common mobile device settings w/ a UI component?  Perhaps you can share a screenshot to demonstrate?

> After this milestone reached, I think that would build up a good ground to add after other features, like some tracking libs like libCMT, LSD-SLAM, ORB-SLAM2.

Definitely!  A good first step would be to add these packages to hunter.  You could open an issue for the ones you are interested in to start with.  I know enough to help with the basics if you need some help, and you can always post a bounty there.

Looking forward to having another user here! ;)  It will motivate me to clean things up a little.

**Comment by headupinclouds** [comment]
I think "Adding Find-Object" should probably move to hunter.  I'll close this for now, and we can continue more high level project discussion (SLAM, etc) in another issue.
