### ISSUE TITLE
Android  + CMake + MS Visual Studio

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#162]
It looks like this would provide functional Android debugging w/ IDE:

https://blogs.msdn.microsoft.com/vcblog/2015/12/15/support-for-android-cmake-projects-in-visual-studio/

---

Update (by Ruslo):
- [x] Simple library
- [x] Create APK
- [x] Polly toolchain
- [x] Test with Hunter
- [x] Visual Studio debugging (set breakpoints)

Low priority:
- [ ] Ninja + toolchain from OpenCV
- [ ] Testing on AppVeyor
##

**Comment by ruslo** [comment]
I've managed to build simple library: http://cgold.readthedocs.io/en/latest/platforms/android/windows.html

Next will take a look at creating APK and adding new toolchain to Polly. However I think testing on AppVeyor may be tricky since we need nonstandard Visual Studio components installed.

**Comment by ruslo** [comment]
List of STL differs a little bit:
- https://github.com/taka-no-me/android-cmake#basic-options
- https://github.com/Microsoft/CMake/blob/feature/VCMDDAndroid/Help/prop_tgt/VC_MDD_ANDROID_USE_OF_STL.rst

**Comment by ruslo** [comment]
There are approach with Ninja as generator: https://github.com/taka-no-me/android-cmake#building-on-windows. Should be more customizable. @headupinclouds I can take a look, let me know if you're interested.

**Comment by ruslo** [comment]
> adding new toolchain to Polly

New toolchains: http://polly.readthedocs.io/en/latest/toolchains/android.html
CGold update: http://cgold.readthedocs.io/en/latest/platforms/android/windows.html

**Comment by ruslo** [comment]
> Test with Hunter

We have to use toolchain file even for projects without C/C++ targets. Have to update HunterGate:
- https://github.com/hunter-packages/gate/commit/abd2dc7bac9df33a4c1aede579b2ed151c8115e2

MSVC_IDE is not defined for Visual Studio MDD toolchain so multi-configuration IDE should be detected in a different way:
- https://github.com/ruslo/hunter/commit/4f3a6803af29b697152abeba1cff31603aee10ff
- http://cgold.readthedocs.io/en/latest/tutorials/build-types.html#detect-multi-single

Simple example with GTest works for me.

**Comment by ruslo** [comment]
> Create APK

So I'm aware of 3 options here:

1) Raw executable (not APK)

Build executable, upload it to device by `adb push` and run. This is not a choice for the Android MDD since `add_executable` will not work: "Currently we only support libraries, object, static, or dynamic." (from [blog](https://blogs.msdn.microsoft.com/vcblog/2015/12/15/support-for-android-cmake-projects-in-visual-studio/)).
- https://github.com/forexample/android-cmake/tree/master/00-console

2) Use [Android-APK](https://github.com/hunter-packages/android-apk) modules to create APK.

This module designed to be used with OpenCV Android toolchain. Issues I've discovered so far:
- this module is designed for Makefile single-configuration generators, need to refactor custom targets so they will work with Visual Studio multi-configuration generator
- this module expect some variables to be defined, e.g. `ANROID_ABI` is not defined in Visual Studio MDD: http://polly.readthedocs.io/en/latest/toolchains/android.html#developer-notes
- https://github.com/forexample/android-cmake/blob/master/01-load-libraries

3) Use [QtAndroidCMake](https://github.com/hunter-packages/qt-android-cmake) module.

This will work only for applications which is based on Qt GUI. Also we need to build Qt with new toolchain. I've tried to run current scheme and it fails, need to investigate.
- https://github.com/forexample/android-cmake/tree/master/05-qt-hellogl2

Will investigate 2) approach.

**Comment by ruslo** [comment]
> Visual Studio debugging (set breakpoints)

Seems related: https://blogs.msdn.microsoft.com/vcblog/2014/12/12/debug-jni-android-applications-using-visual-c-cross-platform-mobile/

**Comment by ruslo** [comment]
> Create APK

Fixed, [v0.15.6](https://github.com/ruslo/hunter/releases/tag/v0.15.6).

**Comment by ruslo** [comment]
> Visual Studio debugging (set breakpoints)

See http://cgold.readthedocs.io/en/latest/platforms/android/windows.html#debugging-with-visual-studio

**Comment by ruslo** [comment]
> However I think testing on AppVeyor may be tricky since we need nonstandard Visual Studio components installed.

We can try RTM image: http://www.appveyor.com/docs/installed-software#visual-studio-2015

**Comment by ruslo** [comment]
Entropy is growing: http://www.mail-archive.com/cmake-developers@cmake.org/msg17052.html
We have to try it too.

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
