### ISSUE TITLE
Test Qt camera

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#42]
From https://github.com/headupinclouds/gatherer/issues/36:

```
QT seems to support camera access on iOS and Android platforms:

    http://doc.qt.io/qt-5/cameraoverview.html
    https://forum.qt.io/topic/41961/accessing-the-android-camera-in-qt/3
```

**Comment by ruslo** [comment]
To investigate: https://github.com/microsoft-mobile/qt-camera-demo

**Comment by headupinclouds** [comment]
Added both qt-camera-demo (src/app/qt-camera-demo) and the stock qt camera sample (src/app/qt-camera) with first draft CMake files.  Currently src/app/qt-camera-demo is failing to build due to missing QtDeclarative libs in the hunter QT build (see: ruslo/hunter#253).  The qt-camera app is building and runs but report the following error:

```
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.camera"
```

And similar message "The camera service is missing" in a pop up dialog.

This SO post seems relevant: http://stackoverflow.com/a/20791976, and seems to suggest a plugin needs to be copied into the same directory.

> "In contrast to user plugins, Qt plugins have to be put into subdirectories matching the plugin type. As we want to deploy the windows platform plugin it has to be put into a "platforms" subdirectory."

There seems to be a standard qt deployment process, and the OS X version I'm initially testing is described more here: 

http://doc.qt.io/qt-5/osx-deployment.html

Links:
http://www.qtcentre.org/threads/61373-default-camera-application(Qt-5-2-0)-is-not-running-on-linux
https://forum.qt.io/topic/52793/raspberry-pi-qt-5-3-2-qt-camera-not-working-no-service-found-for-org-qt-project-qt-camera/6
https://forum.qt.io/topic/42215/camera-does-not-work-on-android/3

**Comment by ruslo** [comment]
Just for the record:
- iOS example works on iPhone but layout didn't survive device rotation and looks ugly in general but camera and widgets work :)
- iOS example on iPad (same code, same project, same device OS) run but camera didn't work. There is no error messages on start but when I switch Back Camera/Front Camera next message appears in log:

```
Failed to create video device input
```

_will push updates soon_

**Comment by ruslo** [comment]
Linux testing: compiles/links fine now but application starts with runtime error:

```
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.camera"
```

I don't know what plugin should be linked, I see only `plugins/mediaservice/libqtmedia_audioengine.a`

**Comment by ruslo** [comment]
I've started new build just to be sure all patches applied fine. Will send updates for src/app/qt-camera when it's done.

**Comment by headupinclouds** [comment]
the qt qml camera samples are working now.  closing.

**Comment by Ramiz-Arshad** [comment]
I am running camera on Linux and getting an error that

> defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.camera"

Here is my Code

```
Camera::Camera(QWidget *parent) :
QMainWindow(parent),
ui(new Ui::Camera)

ui->setupUi(this);
mCamera = new QCamera(this);
recorder = new QMediaRecorder(mCamera,this);
mCameraViewfinder = new QCameraViewfinder(this);
mCameraImageCapture = new QCameraImageCapture(mCamera,this);
mLayout = new QVBoxLayout;

mCamera->setViewfinder(mCameraViewfinder);
mLayout->addWidget(mCameraViewfinder);
ui->scrollArea->setLayout(mLayout);
//mCameraViewfinder->show();
mCamera->start();
```

**.pro file**
```
QT += core gui multimedia multimediawidgets
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets 
TARGET = Camera 
TEMPLATE = app 
DEFINES += QT_DEPRECATED_WARNINGS 
SOURCES += \ main.cpp \ camera.cpp 
HEADERS += \ camera.h 
FORMS += \ camera.ui
```

Any Help?
