### ISSUE TITLE
Create CVPixelBufferRef manually instead of getting it from Qt

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#80]
Since there is a chance that some internal stuff broken (see https://github.com/headupinclouds/gatherer/pull/79#issuecomment-165091028) in Qt after [patching](https://github.com/headupinclouds/gatherer/issues/77#issuecomment-164686603) another approach can be used. Just do map and use pointer to create CVPixelBufferRef manually. Hints:
- http://stackoverflow.com/questions/16475737/convert-uiimage-to-cmsamplebufferref/16487926#16487926
- http://stackoverflow.com/questions/11607753/cvopenglestexturecachecreatetexturefromimage-on-ipad2-is-too-slow-it-needs-almo/11715866#11715866
- https://github.com/BradLarson/GPUImage/blob/92aaa7125780356683137d497e6dd58093823103/framework/Source/GPUImageVideoCamera.m#L609

**Comment by ruslo** [comment]
https://github.com/BradLarson/GPUImage/blob/92aaa7125780356683137d497e6dd58093823103/framework/Source/GPUImageVideoCamera.m#L655

**Comment by headupinclouds** [comment]
I believe the CVPixelBufferRef needs to be created with the `kCVPixelBufferIOSurfacePropertiesKey` attributes for this to work.

That would be specified here:
https://github.com/headupinclouds/gatherer/blob/videofilter/src/app/qmlvideofilter/CVPixelBufferWrapper.mm#L24

Looking in ogles_gpgpu, that is already happening here:

https://github.com/headupinclouds/ogles_gpgpu/blob/hunter/ogles_gpgpu/platform/ios/memtransfer_ios.cpp#L94

and here:

https://github.com/headupinclouds/ogles_gpgpu/blob/hunter/ogles_gpgpu/platform/ios/memtransfer_ios.cpp#L153

Except this code is configured to expect an input `CVPixelBuferRef *`.  It seems we should be able to modify this to accommodate a raw pixel buffer input and then replace the internal `CVPixelBufferCreate` with the `CVPixelBufferCreateWithBytes` you've added in `CVPixelBufferWrapper.h`.

**Comment by ruslo** [comment]
> I believe the CVPixelBufferRef needs to be created with the kCVPixelBufferIOSurfacePropertiesKey attributes for this to work

Ok, will try it

**Comment by headupinclouds** [comment]
Try the latest commit.  I've made a slight modification to the ogles_gpgpu `MemTransferIOS::prepareInput()` class to support raw pixel buffers internally, in addition to the CVPixelBufferRef pointers.  

https://github.com/headupinclouds/ogles_gpgpu/blob/hunter/ogles_gpgpu/platform/ios/memtransfer_ios.cpp#L149

This behavior can be configured using the `MemTransfer:: setUseRawPixels(bool)` method.

https://github.com/headupinclouds/ogles_gpgpu/blob/hunter/ogles_gpgpu/common/gl/memtransfer.h#L92

This basically move the `CVPixelBufferCreateWithBytes` operation you've added inside that class, since it is already creating the attributes and managing associated memory in that code.  It is working well on my iPhone 5s.

**Comment by headupinclouds** [comment]
closing,

**Comment by ruslo** [comment]
So as far as I understand we don't need CVPixelBufferWrapper anymore?

**Comment by ruslo** [comment]
> So as far as I understand we don't need CVPixelBufferWrapper anymore?

Removed: https://github.com/headupinclouds/gatherer/pull/90
